spring:
  application:
    name: news-api
  profiles:
    active: '@activatedProperties@'
  redis:
    host: '127.0.0.1'
    port: 6379
    ttl:
      seconds: 60

news:
  client:
    url: https://gnews.io/api/v4/search
    token: 0a7e7fc424e0ad437902a2a0bd771365
